// lib/install.mjs
import { readFileSync, writeFileSync, mkdirSync, existsSync, copyFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { configDir, pluginDir, loadConfig, saveConfig } from "./config.mjs";

// statusLine command uses the portable env-var form so it works across machines.
const WRAPPER_CMD = "node ${CLAUDE_CONFIG_DIR:-$HOME/.claude}/cyberpunk-hud/statusline.mjs";

export function wrapperPath(env = process.env) {
  return join(pluginDir(env), "statusline.mjs");
}
export function settingsPath(env = process.env) {
  return join(configDir(env), "settings.json");
}

const WRAPPER_SOURCE = `#!/usr/bin/env node
// Auto-generated by 'cyberpunk-hud setup'. Resolves the plugin renderer so that
// settings.json keeps working across plugin version bumps. Do not edit by hand.
import { existsSync, readdirSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

function configDir() { return process.env.CLAUDE_CONFIG_DIR || join(homedir(), ".claude"); }
function safeReaddir(p) { try { return readdirSync(p); } catch { return []; } }

function findRenderer() {
  // 1. dev / non-plugin override
  const dev = process.env.CYBERPUNK_HUD_ROOT;
  if (dev) {
    const f = join(dev, "bin", "cyberpunk-hud.mjs");
    if (existsSync(f)) return f;
  }
  // 2. newest version in the plugin cache: plugins/cache/<marketplace>/cyberpunk-hud/<version>/
  const base = join(configDir(), "plugins", "cache");
  const found = [];
  for (const mkt of safeReaddir(base)) {
    const pdir = join(base, mkt, "cyberpunk-hud");
    for (const ver of safeReaddir(pdir)) {
      const f = join(pdir, ver, "bin", "cyberpunk-hud.mjs");
      if (existsSync(f)) found.push({ ver, f });
    }
  }
  found.sort((a, b) => b.ver.localeCompare(a.ver, undefined, { numeric: true }));
  return found[0]?.f || null;
}

const renderer = findRenderer();
if (renderer) {
  await import(pathToFileURL(renderer).href);
} else {
  process.stdout.write("\\x1b[2mcyberpunk-hud: not found (run /cyberpunk-hud setup)\\x1b[0m");
}
`;

export function writeWrapper(env = process.env) {
  const p = wrapperPath(env);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, WRAPPER_SOURCE);
  return p;
}

export function setup(env = process.env) {
  const cfg = loadConfig(env);
  const sp = settingsPath(env);
  let settings = {};
  try { settings = JSON.parse(readFileSync(sp, "utf8")); } catch { /* new file */ }

  const prev = typeof settings.statusLine?.command === "string" ? settings.statusLine.command : "";
  if (settings.statusLine && (!prev || !prev.includes("cyberpunk-hud"))) {
    cfg.previousStatusLine = settings.statusLine;
  }

  writeWrapper(env);
  if (existsSync(sp) && !existsSync(sp + ".cyberpunk-hud.bak")) copyFileSync(sp, sp + ".cyberpunk-hud.bak");
  mkdirSync(configDir(env), { recursive: true });
  settings.statusLine = { type: "command", command: WRAPPER_CMD };
  writeFileSync(sp, JSON.stringify(settings, null, 2));
  saveConfig(cfg, env);
  return { wrapper: wrapperPath(env), settings: sp };
}

export function restore(env = process.env) {
  const cfg = loadConfig(env);
  const sp = settingsPath(env);
  let settings = {};
  try { settings = JSON.parse(readFileSync(sp, "utf8")); } catch { /* nothing */ }
  if (cfg.previousStatusLine) settings.statusLine = cfg.previousStatusLine;
  else delete settings.statusLine;
  writeFileSync(sp, JSON.stringify(settings, null, 2));
  cfg.previousStatusLine = null;
  saveConfig(cfg, env);
  return sp;
}
